language: python
python:
  - "3.5"
services:
  - postgresql
  - elasticsearch
cache:
  - pip
env:
  - CFLAGS=-O0
install:
  - pip install -U pip wheel
  - pip install coveralls
  - pip install -r requirements.txt
before_script:
  - psql -c "create user jeito password 'jeito' createdb;" -U postgres
  - psql -c "create database jeito owner jeito;" -U postgres
  - cp client_id.json.test client_id.json
  - ./manage.py collectstatic --settings=jeito.test_settings --noinput
script:
  - flake8
  - coverage run manage.py test --settings=jeito.test_settings
after_success:
  - coveralls
